### PR TITLE
Automation Editor: add missing 'autocomplete suggestions'

### PR DESCRIPTION
**Pull request by beatbesmer**
According https://cerb.ai/docs/sheets/#time-elapsed

### CODE REVIEW

**Review by beatbesmer — COMMENTED** [review]
Seems as it didn't remove the newline.
@jstanden Let me know if this is a problem and if i should change anything in future related to this

**Comment by jstanden** [comment]
Hi Beat! Nice work. I'll get this merged.

**Comment by beatbesmer** [comment]
@jstanden as i used the wront repo (cerb-release), i'll remove this pull-request. There's a new pull-request which should 
- use the correct repo (jstanden/cerb)
- includes all keys for 'Maps'

**Comment by jstanden** [comment]
Hey Beat,

These commits have been squashed and merged into jstanden/cerb:10.2

Thanks again!

**Pull request closed without merging**
