### PR TITLE
Automation autocomplete suggestions for Maps (await:form:elements:map)

### PR DESCRIPTION
**Pull request by beatbesmer**
All keys documented under https://cerb.ai/docs/maps/ have been integrated.
Wherever possible with placeholders, examples and support for autocompletion of records with type 'cerb-uri'

I'm open for feedbacks regarding improvment of examples and translations :)

### CODE REVIEW

**Comment by beatbesmer** [comment]
Hmm... i guess the files added by composer have been included as well :(
Let me know if you can work with this PR. Basically, i only touched '...the interaction.worker.php'

**Comment by jstanden** [comment]
Hi Beat!

I'll pull this branch locally and rebase it, but keep your attribution.

Thanks for taking the time to do this. :)

**Comment by jstanden** [comment]
k! I did a `git rebase 10.2` and it cleaned everything up. I'm merging your patches now.

Make sure the next fork is against `10.2` and not `v10.2`, then we can use the GitHub approve/merges. :)

**Comment by beatbesmer** [comment]
> Make sure the next fork is against `10.2` and not `v10.2`, then we can use the GitHub approve/merges. :)

Someday I will 'git' this right too 🙄

**Comment by jstanden** [comment]
Hey Beat,

These commits have been squashed and merged into jstanden/cerb:10.2

Thanks again!

**Pull request closed without merging**
